/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '/easy/dom-teleport': RouteRecordInfo<'/easy/dom-teleport', '/easy/dom-teleport', Record<never, never>, Record<never, never>>,
    '/easy/dynamic-css': RouteRecordInfo<'/easy/dynamic-css', '/easy/dynamic-css', Record<never, never>, Record<never, never>>,
    '/easy/hello-world': RouteRecordInfo<'/easy/hello-world', '/easy/hello-world', Record<never, never>, Record<never, never>>,
    '/easy/life-callback': RouteRecordInfo<'/easy/life-callback', '/easy/life-callback', Record<never, never>, Record<never, never>>,
    '/easy/next-tick': RouteRecordInfo<'/easy/next-tick', '/easy/next-tick', Record<never, never>, Record<never, never>>,
    '/easy/ref-family': RouteRecordInfo<'/easy/ref-family', '/easy/ref-family', Record<never, never>, Record<never, never>>,
  }
}
