/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/capitalize': RouteRecordInfo<'/vuejs-challenges/capitalize', '/vuejs-challenges/capitalize', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/dependency-injection': RouteRecordInfo<'/vuejs-challenges/dependency-injection', '/vuejs-challenges/dependency-injection', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/dom-teleport': RouteRecordInfo<'/vuejs-challenges/dom-teleport', '/vuejs-challenges/dom-teleport', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/dynamic-css': RouteRecordInfo<'/vuejs-challenges/dynamic-css', '/vuejs-challenges/dynamic-css', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/functional-component': RouteRecordInfo<'/vuejs-challenges/functional-component', '/vuejs-challenges/functional-component', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/hello-world': RouteRecordInfo<'/vuejs-challenges/hello-world', '/vuejs-challenges/hello-world', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/key-modifiers': RouteRecordInfo<'/vuejs-challenges/key-modifiers', '/vuejs-challenges/key-modifiers', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/life-callback': RouteRecordInfo<'/vuejs-challenges/life-callback', '/vuejs-challenges/life-callback', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/losing-reactivity': RouteRecordInfo<'/vuejs-challenges/losing-reactivity', '/vuejs-challenges/losing-reactivity', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/next-tick': RouteRecordInfo<'/vuejs-challenges/next-tick', '/vuejs-challenges/next-tick', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/optimiza-performance-directive': RouteRecordInfo<'/vuejs-challenges/optimiza-performance-directive', '/vuejs-challenges/optimiza-performance-directive', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/prevent-event-propagation': RouteRecordInfo<'/vuejs-challenges/prevent-event-propagation', '/vuejs-challenges/prevent-event-propagation', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/prop-validation': RouteRecordInfo<'/vuejs-challenges/prop-validation', '/vuejs-challenges/prop-validation', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/ref-family': RouteRecordInfo<'/vuejs-challenges/ref-family', '/vuejs-challenges/ref-family', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/render-function': RouteRecordInfo<'/vuejs-challenges/render-function', '/vuejs-challenges/render-function', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/shallow-ref': RouteRecordInfo<'/vuejs-challenges/shallow-ref', '/vuejs-challenges/shallow-ref', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/until-counter': RouteRecordInfo<'/vuejs-challenges/until-counter', '/vuejs-challenges/until-counter', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/use-counter': RouteRecordInfo<'/vuejs-challenges/use-counter', '/vuejs-challenges/use-counter', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/use-local-storage': RouteRecordInfo<'/vuejs-challenges/use-local-storage', '/vuejs-challenges/use-local-storage', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/use-toggle': RouteRecordInfo<'/vuejs-challenges/use-toggle', '/vuejs-challenges/use-toggle', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/v-debounce-click': RouteRecordInfo<'/vuejs-challenges/v-debounce-click', '/vuejs-challenges/v-debounce-click', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/v-focus': RouteRecordInfo<'/vuejs-challenges/v-focus', '/vuejs-challenges/v-focus', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/watch-family': RouteRecordInfo<'/vuejs-challenges/watch-family', '/vuejs-challenges/watch-family', Record<never, never>, Record<never, never>>,
    '/vuejs-challenges/writable-computed': RouteRecordInfo<'/vuejs-challenges/writable-computed', '/vuejs-challenges/writable-computed', Record<never, never>, Record<never, never>>,
  }
}
